"use client";

import { useState, type FormEvent } from "react";
import { AiProfilePanel } from "./customer-development-panels";
import type { AccountItem, ActivityItem, ContactItem } from "@/lib/types";
import { accountEngagementDates, captureOriginalSource, CONNECTION_CONFIDENCES, CONNECTION_KINDS, connectionsWorthExploring, FACT_KINDS, FACT_STATUSES, INTRODUCTION_STATUSES, NURTURE_APPROACHES, outreachGuard } from "@/lib/relationship-context";
import { useLocalDay } from "@/lib/use-local-day";
import { metricDay, validMetricDate } from "@/lib/gtm-metrics";

type Fact = NonNullable<AccountItem["contextFacts"]>[number];
type Connection = NonNullable<AccountItem["connections"]>[number];
type Plan = NonNullable<AccountItem["nurturePlan"]>;
type Save = (changes: Partial<AccountItem>) => void;
const css = (name: string) => `relationship-context-${name}`;
const topicOptions = ["Organization", "Buyer priorities", "Original problem", "Systems", "Stakeholders", "Previous discussions", "Constraints", "Open question", "Customer commitment", "Spej commitment", "Next action", "Verified outcome"];
const knownDate = (value: string | undefined) => value || "Not recorded";
function localCaptureDay(value: string | undefined) {
  if (!value || !validMetricDate(value.slice(0, 10)) || !Number.isFinite(Date.parse(value))) return "";
  return metricDay(new Date(value));
}
const personName = (id: string | undefined, contacts: ContactItem[]) => id ? contacts.find((person) => person.id === id)?.name || "Person no longer available" : "Not recorded";

function EvidenceForm({ onSave }: { onSave: (fact: Fact) => void }) {
  const today = useLocalDay();
  const [draft, setDraft] = useState({ topic: "Buyer priorities", text: "", kind: "Customer statement" as Fact["kind"], sourceLabel: "", sourceDate: "", status: "Current" as Fact["status"] });
  const [error, setError] = useState("");
  const submit = (event: FormEvent) => {
    event.preventDefault();
    if (!draft.text.trim() || !draft.sourceLabel.trim()) return setError("Add the context and where it came from.");
    if (draft.sourceDate > today) return setError("The original source date cannot be in the future.");
    onSave({ ...draft, text: draft.text.trim(), sourceLabel: draft.sourceLabel.trim(), id: crypto.randomUUID(), capturedAt: new Date().toISOString() });
    setDraft((current) => ({ ...current, text: "", sourceLabel: "", sourceDate: "", status: "Current" })); setError("");
  };
  return <details className={css("section")}><summary>Add sourced context</summary><form className={css("form")} onSubmit={submit}>
    <div className={css("grid")}><label>Context topic<select value={draft.topic} onChange={(e) => setDraft({ ...draft, topic: e.target.value })}>{topicOptions.map((topic) => <option key={topic}>{topic}</option>)}</select></label><label>Statement type<select value={draft.kind} onChange={(e) => setDraft({ ...draft, kind: e.target.value as Fact["kind"] })}>{FACT_KINDS.map((kind) => <option key={kind}>{kind}</option>)}</select></label></div>
    <label>Context or fact<textarea required maxLength={2000} value={draft.text} onChange={(e) => setDraft({ ...draft, text: e.target.value })} placeholder="Record what was actually said; label interpretations separately."/></label>
    <div className={css("grid")}><label>Source reference<input required maxLength={240} value={draft.sourceLabel} onChange={(e) => setDraft({ ...draft, sourceLabel: e.target.value })} placeholder="Meeting title, email subject, or source note"/></label><label>Original source date (if known)<input type="date" max={today} value={draft.sourceDate} onChange={(e) => setDraft({ ...draft, sourceDate: e.target.value })}/></label><label>Evidence status<select value={draft.status} onChange={(e) => setDraft({ ...draft, status: e.target.value as Fact["status"] })}>{FACT_STATUSES.map((status) => <option key={status}>{status}</option>)}</select></label></div>
    <p className={css("muted")}>The capture time is saved separately. New context is added to the history; a later statement does not erase an earlier one.</p>
    {error && <p className={css("error")} role="alert">{error}</p>}<div className={css("actions")}><button className="button button-primary">Save context</button></div>
  </form></details>;
}

function ConnectionForm({ account, accounts, contacts, initial, onSave, onCancel }: { account: AccountItem; accounts: AccountItem[]; contacts: ContactItem[]; initial?: Connection; onSave: (connection: Connection) => void; onCancel?: () => void }) {
  const today = useLocalDay();
  const [draft, setDraft] = useState<Connection>(initial || { id: "", fromContactId: "", viaContactId: "", toAccountId: account.id, toContactId: "", context: "", kind: "Possible introduction", introductionStatus: "Not requested", validator: "", lastInteractionDate: "", relevance: "", nextStep: "", dueDate: "", evidence: "", evidenceDate: "", confidence: "Unknown" });
  const [error, setError] = useState("");
  const update = (changes: Partial<Connection>) => setDraft((current) => ({ ...current, ...changes }));
  const submit = (event: FormEvent) => {
    event.preventDefault();
    if (!draft.fromContactId || (!draft.toAccountId && !draft.toContactId)) return setError("Select a starting person and a target account or person.");
    if (!draft.context.trim() || !draft.relevance.trim() || !draft.nextStep.trim() || !draft.evidence.trim()) return setError("Add the connection context, relevance, next step, and source evidence.");
    if (draft.lastInteractionDate > today || draft.evidenceDate > today) return setError("Interaction and evidence dates cannot be in the future.");
    if (draft.fromContactId === draft.toContactId || draft.fromContactId === draft.viaContactId || (draft.toContactId && draft.toContactId === draft.viaContactId)) return setError("Each person in the introduction path must be distinct.");
    onSave({ ...draft, id: initial?.id || crypto.randomUUID() });
  };
  const people = contacts.filter((person) => !person.archivedAt || [draft.fromContactId, draft.viaContactId, draft.toContactId].includes(person.id));
  return <form className={css("form")} onSubmit={submit}>
    <div className={css("grid")}><label>Starting person<select required value={draft.fromContactId || ""} onChange={(e) => update({ fromContactId: e.target.value })}><option value="">Select existing person</option>{people.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select></label><label>Intermediary (optional)<select value={draft.viaContactId || ""} onChange={(e) => update({ viaContactId: e.target.value })}><option value="">Direct connection</option>{people.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select></label><label>Target account<select value={draft.toAccountId || ""} onChange={(e) => update({ toAccountId: e.target.value, toContactId: "" })}><option value="">Person-level connection</option>{accounts.filter((item) => !item.archivedAt || item.id === draft.toAccountId).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Target person (optional)<select value={draft.toContactId || ""} onChange={(e) => update({ toContactId: e.target.value })}><option value="">No individual selected</option>{people.filter((person) => !draft.toAccountId || person.accountId === draft.toAccountId || person.id === draft.toContactId).map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select></label></div>
    <label>Relationship context<textarea required maxLength={1200} value={draft.context} onChange={(e) => update({ context: e.target.value })} placeholder="How these people know each other; community or event context if relevant."/></label>
    <div className={css("grid")}><label>Connection type<select value={draft.kind} onChange={(e) => update({ kind: e.target.value as Connection["kind"] })}>{CONNECTION_KINDS.map((kind) => <option key={kind}>{kind}</option>)}</select></label><label>Introduction status<select value={draft.introductionStatus} onChange={(e) => update({ introductionStatus: e.target.value as Connection["introductionStatus"] })}>{INTRODUCTION_STATUSES.map((status) => <option key={status}>{status}</option>)}</select></label><label>Who can validate this<input maxLength={160} value={draft.validator} onChange={(e) => update({ validator: e.target.value })}/></label><label>Last actual interaction (if known)<input type="date" max={today} value={draft.lastInteractionDate} onChange={(e) => update({ lastInteractionDate: e.target.value })}/></label></div>
    <label>Why this connection matters<textarea required maxLength={1200} value={draft.relevance} onChange={(e) => update({ relevance: e.target.value })}/></label><label>Next validation or introduction step<input required maxLength={600} value={draft.nextStep} onChange={(e) => update({ nextStep: e.target.value })}/></label>
    <div className={css("grid")}><label>Next-step date (optional)<input type="date" value={draft.dueDate} onChange={(e) => update({ dueDate: e.target.value })}/></label><label>Evidence confidence<select value={draft.confidence} onChange={(e) => update({ confidence: e.target.value as Connection["confidence"] })}>{CONNECTION_CONFIDENCES.map((confidence) => <option key={confidence}>{confidence}</option>)}</select></label><label>Source evidence<input required maxLength={1200} value={draft.evidence} onChange={(e) => update({ evidence: e.target.value })} placeholder="Source note or reference supporting this connection"/></label><label>Evidence date (if known)<input type="date" max={today} value={draft.evidenceDate} onChange={(e) => update({ evidenceDate: e.target.value })}/></label></div>
    <p className={css("muted")}>Record an introduction as completed or accepted only when that happened. Connections do not create leads, opportunities, or forecast revenue.</p>{error && <p className={css("error")} role="alert">{error}</p>}<div className={css("actions")}>{onCancel && <button type="button" className="button button-ghost" onClick={onCancel}>Cancel connection edit</button>}<button className="button button-primary">Save connection</button></div>
  </form>;
}

function NurtureForm({ account, onSave }: { account: AccountItem; onSave: Save }) {
  const [draft, setDraft] = useState<Plan>(account.nurturePlan || { approach: "Deferred", owner: account.owner, nextAction: "", dueDate: "", trigger: "", reason: "", desiredOutcome: "", pauseCondition: "", state: "Active" });
  const [error, setError] = useState("");
  const update = (changes: Partial<Plan>) => setDraft((current) => ({ ...current, ...changes }));
  const submit = (event: FormEvent) => {
    event.preventDefault();
    if (![draft.owner, draft.nextAction, draft.reason, draft.desiredOutcome, draft.pauseCondition].every((value) => value.trim())) return setError("Add an owner, action, reason, desired outcome, and pause condition.");
    if (!draft.dueDate && !draft.trigger.trim()) return setError("Set a due date or a specific review trigger.");
    onSave({ nurturePlan: { ...draft, owner: draft.owner.trim(), nextAction: draft.nextAction.trim() } }); setError("");
  };
  return <form className={css("form")} onSubmit={submit}><div className={css("grid")}><label>Nurture approach<select value={draft.approach} onChange={(e) => update({ approach: e.target.value as Plan["approach"] })}>{NURTURE_APPROACHES.map((approach) => <option key={approach}>{approach}</option>)}</select></label><label>Plan state<select value={draft.state} onChange={(e) => update({ state: e.target.value as Plan["state"] })}><option>Active</option><option>Paused</option></select></label><label>Accountable owner<input required maxLength={120} value={draft.owner} onChange={(e) => update({ owner: e.target.value })}/></label><label>Next useful action<input required maxLength={600} value={draft.nextAction} onChange={(e) => update({ nextAction: e.target.value })}/></label><label>Review date (or provide a trigger)<input type="date" value={draft.dueDate} onChange={(e) => update({ dueDate: e.target.value })}/></label><label>Review trigger<input maxLength={600} value={draft.trigger} onChange={(e) => update({ trigger: e.target.value })} placeholder="After the buyer's system migration is complete"/></label></div><label>Why this matters now<textarea required maxLength={1000} value={draft.reason} onChange={(e) => update({ reason: e.target.value })}/></label><label>Outcome needed to move forward<input required maxLength={600} value={draft.desiredOutcome} onChange={(e) => update({ desiredOutcome: e.target.value })}/></label><label>When to pause or park this plan<input required maxLength={600} value={draft.pauseCondition} onChange={(e) => update({ pauseCondition: e.target.value })}/></label>{error && <p className={css("error")} role="alert">{error}</p>}<div className={css("actions")}><button className="button button-primary">Save nurture plan</button></div></form>;
}

function HoldForm({ account, onSave }: { account: AccountItem; onSave: Save }) {
  const [draft, setDraft] = useState(account.outreachHold || { active: true, reason: "", until: "", releaseCondition: "" });
  const [error, setError] = useState("");
  const submit = (event: FormEvent) => {
    event.preventDefault();
    if (!draft.reason.trim() || !draft.releaseCondition.trim()) return setError("Record the reason and what must happen before outreach resumes.");
    onSave({ outreachHold: { ...draft, active: true, reason: draft.reason.trim(), releaseCondition: draft.releaseCondition.trim() } }); setError("");
  };
  return <form className={css("form")} onSubmit={submit}><label>Outreach hold reason<textarea required maxLength={1000} value={draft.reason} onChange={(e) => setDraft({ ...draft, reason: e.target.value })} placeholder="Who requested the pause and what coordination is needed?"/></label><div className={css("grid")}><label>Hold review date (optional)<input type="date" value={draft.until} onChange={(e) => setDraft({ ...draft, until: e.target.value })}/></label><label>Condition for resuming outreach<input required maxLength={1000} value={draft.releaseCondition} onChange={(e) => setDraft({ ...draft, releaseCondition: e.target.value })}/></label></div><p className={css("muted")}>Passing the review date does not release the hold. A teammate must explicitly resolve it after the condition is met.</p>{error && <p className={css("error")} role="alert">{error}</p>}<div className={css("actions")}><button className="button button-primary">{account.outreachHold?.active ? "Update outreach hold" : "Save outreach hold"}</button></div></form>;
}

export function RelationshipContextPanel({ account, accounts, contacts, activities, onSave }: { account: AccountItem; accounts: AccountItem[]; contacts: ContactItem[]; activities: ActivityItem[]; onSave: Save }) {
  const today = useLocalDay();
  const [editingConnection, setEditingConnection] = useState<string | null>(null);
  const [addingConnection, setAddingConnection] = useState(false);
  const origin = account.originalSource || captureOriginalSource(account);
  const engagement = accountEngagementDates(account, activities, today);
  const guard = outreachGuard(account, activities, today);
  const facts = account.contextFacts || [];
  const connections = connectionsWorthExploring(account, accounts, contacts);
  const saveConnection = (connection: Connection) => { onSave({ connections: [...(account.connections || []).filter((item) => item.id !== connection.id), connection] }); setEditingConnection(null); setAddingConnection(false); };
  return <section className={css("panel")} aria-label={`Relationship context for ${account.name}`}>
    <div><h4>Account brief and relationship context</h4><p className={css("muted")}>Keep the source, evidence, relationship paths, and next useful action together.</p></div>
    <AiProfilePanel account={account} onSave={onSave}/>
    <section className={css("section")}><h4>Original relationship source</h4><p>{origin.source || "Source not recorded"} · {origin.acquisitionMotion || "Unclassified"}</p><dl className={css("dates")}><div><dt>Original source date</dt><dd>{knownDate(origin.sourceDate)}</dd></div><div><dt>Originating person</dt><dd>{personName(origin.originatingContactId, contacts)}</dd></div><div><dt>Original referrer</dt><dd>{personName(origin.referrerContactId, contacts)}</dd></div></dl><p className={css("muted")}>The original source is retained when account details change. Record later introductions and influence in Connections.</p>{origin.sourceArtifactId && <p>Source evidence linked to the original record.</p>}</section>
    <section className={css("section")}><h4>Engagement dates</h4><dl className={css("dates")}><div><dt>Last buyer response</dt><dd>{knownDate(engagement.lastBuyerResponse)}</dd></div><div><dt>Last seller outreach</dt><dd>{knownDate(engagement.lastSellerOutreach)}</dd></div><div><dt>Last substantive conversation</dt><dd>{knownDate(engagement.lastSubstantiveConversation)}</dd></div><div><dt>Next agreed step</dt><dd>{knownDate(engagement.nextAgreedStep)}</dd></div><div><dt>Last captured or imported</dt><dd>{knownDate(localCaptureDay(engagement.lastCapturedAt))}</dd></div></dl><p className={css("muted")}>Capture dates do not refresh the original conversation or buyer-response date.</p></section>
    <section><h4>Sourced account context</h4>{facts.some((fact) => fact.status === "Conflicting") && <p className={css("notice")}>Conflicting evidence needs review. Both versions remain in the history until a teammate resolves them.</p>}<div className={css("facts")}>{facts.map((fact) => <article className={css("record")} key={fact.id}><header><strong>{fact.topic}</strong><span className={css("badge")}>{fact.kind} · {fact.status}</span></header><p>{fact.text}</p><small>Source: {fact.sourceLabel} · Original date: {knownDate(fact.sourceDate)} · Captured: {knownDate(localCaptureDay(fact.capturedAt))}</small><div className={css("actions")}>{FACT_STATUSES.filter((status) => status !== fact.status).map((status) => <button type="button" className="button button-ghost" key={status} onClick={() => onSave({ contextFacts: facts.map((item) => item.id === fact.id ? { ...item, status } : item) })}>Mark {status.toLowerCase()}</button>)}</div></article>)}</div>{!facts.length && <p className={css("muted")}>No sourced facts yet. Add buyer priorities, relevant systems, commitments, and open questions as they become known.</p>}<EvidenceForm onSave={(fact) => onSave({ contextFacts: [...facts, fact] })}/></section>
    <section className={css("section")}><h4>Outreach coordination</h4>{guard.blocked ? <div className={css("notice")}>{guard.reasons.map((reason) => <p key={reason}>{reason}</p>)}</div> : <p>No recorded hold or recent activity currently blocks a routine outreach prompt.</p>}{account.outreachHold && <><p><b>{account.outreachHold.active ? "Hold condition" : "Resolved hold"}:</b> {account.outreachHold.releaseCondition}</p><p className={css("muted")}>Review date: {knownDate(account.outreachHold.until)} · Reason: {account.outreachHold.reason}</p>{account.outreachHold.active && <button className="button button-secondary" onClick={() => onSave({ outreachHold: { ...account.outreachHold!, active: false } })}>Condition met — resolve outreach hold</button>}</>}<details><summary>{account.outreachHold?.active ? "Edit hold details" : "Record an outreach hold"}</summary><HoldForm key={`${account.id}:${Boolean(account.outreachHold?.active)}`} account={account} onSave={onSave}/></details></section>
    <section className={css("section")}><h4>Context-based nurture plan</h4>{account.nurturePlan ? <><p><b>{account.nurturePlan.approach} · {account.nurturePlan.state}</b> · {account.nurturePlan.owner}</p><p>{account.nurturePlan.nextAction}</p><p className={css("muted")}>Review: {account.nurturePlan.dueDate || account.nurturePlan.trigger || "Not set"} · Outcome: {account.nurturePlan.desiredOutcome}</p></> : <p className={css("muted")}>Set a specific action and a reason to continue, with a date or a meaningful trigger.</p>}<details><summary>{account.nurturePlan ? "Edit nurture plan" : "Add nurture plan"}</summary><NurtureForm key={`${account.id}:${JSON.stringify(account.nurturePlan)}`} account={account} onSave={onSave}/></details></section>
    <section><h4>Connections and later influence</h4><div className={css("list")}>{connections.map((item) => <article className={css("record")} key={item.connection.id}><header><strong>{item.path}</strong><span className={css("badge")}>{item.connection.kind} · {item.connection.introductionStatus}</span></header><p>{item.connection.context}</p><p><b>Why:</b> {item.reason}</p><p><b>Next:</b> {item.nextStep} · {knownDate(item.connection.dueDate)}</p><small>Validation contact: {item.connection.validator || "Not recorded"} · Confidence: {item.connection.confidence} · Last interaction: {knownDate(item.connection.lastInteractionDate)}</small><small>Evidence: {item.connection.evidence || "Not recorded"} · {knownDate(item.connection.evidenceDate)}</small>{item.referenceIssues.length > 0 && <p className={css("notice")}>{item.referenceIssues.join(" ")}</p>}<button className="button button-ghost" onClick={() => setEditingConnection(editingConnection === item.connection.id ? null : item.connection.id)}>Edit connection</button>{editingConnection === item.connection.id && <ConnectionForm account={account} accounts={accounts} contacts={contacts} initial={item.connection} onSave={saveConnection} onCancel={() => setEditingConnection(null)}/>}</article>)}</div>{!connections.length && <p className={css("muted")}>No connections recorded. Link existing people to a specific path, reason, and next step.</p>}<button className="button button-secondary" aria-expanded={addingConnection} onClick={() => setAddingConnection(!addingConnection)}>{addingConnection ? "Cancel new connection" : "Add connection"}</button>{addingConnection && <ConnectionForm account={account} accounts={accounts} contacts={contacts} onSave={saveConnection}/>}</section>
  </section>;
}

export function RelationshipContextWorkspace({ view, accounts, contacts, activities, query = "", onOpenAccount, onOpenContact }: { view: "connections" | "nurture" | "weekly"; accounts: AccountItem[]; contacts: ContactItem[]; activities: ActivityItem[]; query?: string; onOpenAccount: (id: string) => void; onOpenContact?: (id: string) => void }) {
  const today = useLocalDay();
  const [status, setStatus] = useState("");
  const [approach, setApproach] = useState("");
  const [method, setMethod] = useState("");
  const active = accounts.filter((account) => !account.archivedAt);
  const matches = (text: string) => text.toLowerCase().includes(query.trim().toLowerCase());
  if (view === "connections") {
    const connections = active.flatMap((account) => connectionsWorthExploring(account, accounts, contacts).map((item) => ({ ...item, account }))).filter((item) => (!status || item.connection.introductionStatus === status) && matches(`${item.account.name} ${item.path} ${item.reason} ${item.nextStep}`));
    return <section className={css("workspace")} aria-label="Connections worth exploring"><div><h2>Connections worth exploring</h2><p className={css("muted")}>Review the path, the reason, and the next step. A possible route is not evidence of buyer interest.</p></div><div className={css("filters")}><label>Introduction lifecycle<select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All introduction statuses</option>{INTRODUCTION_STATUSES.map((value) => <option key={value}>{value}</option>)}</select></label></div>{connections.length ? <div className={css("list")}>{connections.map((item) => <article className={css("record")} key={`${item.account.id}:${item.connection.id}`}><header><strong>{item.path}</strong><span className={css("badge")}>{item.connection.introductionStatus} · {item.connection.confidence} confidence</span></header><p>{item.connection.kind} · Recorded on {item.account.name}</p><p><b>Reason:</b> {item.reason}</p><p><b>Next step:</b> {item.nextStep} · {knownDate(item.connection.dueDate)}</p>{item.reviewRequired && <p className={css("notice")}>Validate this route before requesting an introduction. {item.referenceIssues.join(" ")}</p>}<button className="button button-secondary" onClick={() => onOpenAccount(item.account.id)}>Open account and connection</button></article>)}</div> : <div className={css("empty")}><h3>No matching connections yet</h3><p>Open an account and add a connection using people already in CRM. Record community and event context there without turning an audience into leads.</p></div>}</section>;
  }
  if (view === "nurture") {
    const rows = active.filter((account) => (account.nurturePlan || account.status === "Nurture") && (!status || account.nurturePlan?.state === status) && (!approach || account.nurturePlan?.approach === approach) && matches(`${account.name} ${account.owner} ${account.nurturePlan?.nextAction || ""} ${account.nurturePlan?.trigger || ""}`)).sort((a, b) => (a.nurturePlan?.dueDate || "9999").localeCompare(b.nurturePlan?.dueDate || "9999"));
    const people = contacts.filter((person) => !person.archivedAt && person.nurture && active.some((account) => account.id === person.accountId) && (!method || person.nurture.method === method) && (!status || person.nurture.state === status) && matches(`${person.name} ${person.nurture.owner} ${person.nurture.campaign}`));
    return <section className={css("workspace")} aria-label="Nurture plans"><div><h2>Nurture with a reason</h2><p className={css("muted")}>Separate person-level campaigns from personal relationship building. Plans do not send messages.</p></div><label>Person-level method<select value={method} onChange={(e) => setMethod(e.target.value)}><option value="">All methods</option><option>Personal</option><option>Campaign</option><option>Coordinated mix</option></select></label><div className={css("list")}>{people.map((person) => <article className={css("record")} key={person.id}><header><strong>{person.name}</strong><span>{person.nurture!.method} · {person.nurture!.state}</span></header><p>Owner: {person.nurture!.owner || "Not set"} · Campaign: {person.nurture!.campaign || "None"}</p><p>{person.nurture!.channel}: {person.nurture!.nextAction || "Next action needed"} · {person.nurture!.dueDate || person.nurture!.trigger || "Review needed"}</p><p>{person.nurture!.coordination}</p><button className="button button-secondary" onClick={() => onOpenContact ? onOpenContact(person.id) : onOpenAccount(person.accountId)}>Review person plan</button></article>)}</div>{!people.length && <p className={css("muted")}>No matching person-level plans. Add one in CRM → People → Set nurture approach.</p>}<h3>Account-level relationship plans</h3><div className={css("filters")}><label>Nurture state<select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All plan states</option><option>Active</option><option>Paused</option><option>Ended</option></select></label><label>Nurture approach<select value={approach} onChange={(e) => setApproach(e.target.value)}><option value="">All approaches</option>{NURTURE_APPROACHES.map((value) => <option key={value}>{value}</option>)}</select></label></div>{rows.length ? <div className={css("list")}>{rows.map((account) => { const plan = account.nurturePlan; const guard = outreachGuard(account, activities, today); return <article className={css("record")} key={account.id}><header><strong>{account.name}</strong><span className={css("badge")}>{plan ? `${plan.approach} · ${plan.state}` : "Plan needed"}</span></header><p>Owner: {plan?.owner || account.owner}</p><p><b>Next action:</b> {plan?.nextAction || "Add a specific action"}</p><p><b>Review:</b> {plan?.dueDate || plan?.trigger || "Add a date or trigger"}</p>{plan && <><p><b>Reason:</b> {plan.reason}</p><p><b>Desired outcome:</b> {plan.desiredOutcome}</p><p><b>Pause when:</b> {plan.pauseCondition}</p></>}{guard.blocked && <p className={css("notice")}>{guard.reasons.join(" ")}</p>}<button className="button button-secondary" onClick={() => onOpenAccount(account.id)}>Review account plan</button></article>; })}</div> : <div className={css("empty")}><h3>No matching nurture plans</h3><p>Open an account to set an owner, next action, review trigger, and a condition for pausing.</p></div>}</section>;
  }
  const weekStart = new Date(`${today}T12:00:00`); weekStart.setDate(weekStart.getDate() - 7); const since = `${weekStart.getFullYear()}-${String(weekStart.getMonth() + 1).padStart(2, "0")}-${String(weekStart.getDate()).padStart(2, "0")}`;
  const rows = active.map((account) => {
    const reasons: string[] = [];
    const conflictCount = account.contextFacts?.filter((fact) => fact.status === "Conflicting").length || 0;
    const recentFacts = account.contextFacts?.filter((fact) => localCaptureDay(fact.capturedAt) >= since && localCaptureDay(fact.capturedAt) <= today).length || 0;
    const plan = account.nurturePlan;
    if (conflictCount) reasons.push(`${conflictCount} conflicting statement${conflictCount === 1 ? "" : "s"} need a decision`);
    if (recentFacts) reasons.push(`${recentFacts} context update${recentFacts === 1 ? "" : "s"} captured in the past seven days`);
    if (account.outreachHold?.active) reasons.push(`Outreach hold: ${account.outreachHold.reason}`);
    if (plan?.state === "Active" && plan.dueDate && plan.dueDate <= today) reasons.push(`Nurture review due: ${plan.nextAction}`);
    if (plan?.state === "Paused") reasons.push(`Parked: ${plan.pauseCondition}`);
    if (account.status === "Nurture" && !plan) reasons.push("Nurture relationship needs a specific plan");
    for (const connection of account.connections || []) if (["Offered", "Requested"].includes(connection.introductionStatus) && (!connection.dueDate || connection.dueDate <= today)) reasons.push(`${connection.introductionStatus} introduction: ${connection.nextStep || "Set the next step"}`);
    return { account, reasons };
  }).filter(({ account, reasons }) => reasons.length > 0 && matches(`${account.name} ${account.owner} ${reasons.join(" ")}`));
  return <section className={css("workspace")} aria-label="Weekly relationship review"><div><h2>Weekly relationship review</h2><p className={css("muted")}>Review recent context, unresolved evidence, pending introductions, holds, and plans to advance or park. These are views of the same account records.</p></div>{rows.length ? <div className={css("list")}>{rows.map(({ account, reasons }) => <article className={css("record")} key={account.id}><header><strong>{account.name}</strong><span className={css("badge")}>{account.owner}</span></header>{reasons.map((reason) => <p key={reason}>{reason}</p>)}<button className="button button-secondary" onClick={() => onOpenAccount(account.id)}>Review account</button></article>)}</div> : <div className={css("empty")}><h3>No relationship review items</h3><p>New sourced context, unresolved holds, and due nurture or introduction steps will appear here.</p></div>}</section>;
}
